# Site settings
title: Learn ScrollMagic the Hard Way
email: hello@justinmarsan.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing what I learn about ScrollMagic along the way, with exercises, explanations and tips. Feedback and pull requests are more than welcome !
baseurl: "/learn-scroll-magic" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: justinmarsan
github_username:  justinmarsan

# Build settings
markdown: kramdown
highlighter: true
